export type RestructuredItems = {
    buildings: any
    boosters: any
    farms: any
    decos: any
    habitats: any
    obstacles: any
    lands: any
    socialBuildings: any
    kindergartens: any
    lostitems: any
    crosspromotions: any
    promoislands: any
    collectislands: any
    dragonariums: any
    atrezzos: any
    misteryEggs: any
    promos: any
    units: any
    popups: any
    deusislands: any
    chestcontainers: any
    halloweenIslands: any
    dwportals: any
    progressiveIslands: any
    memeGenerators: any
    mageShrines: any
    gdTowers: any
    gridIslands: any
    cumCalendarIslands: any
    traderIslands: any
    dragonCinemas: any
    fogIslands: any
    heroicRaces: any
    mazeIslands: any
    towerIslands: any
    eventIslands: any
    treeOfLives: any
    alliancePortals: any
    burrows: any
    allianceRaces: any
    collectibles: any
    greenhouses: any
    puzzleIslands: any
    breedingIslands: any
    dragonObstacles: any
    runnerIslands: any
    dragonTvs: any
    offerwalls: any
    orbHabitats: any
    wizardsCaves: any
    teaserIslands: any
    brandDecos: any
    dragons: any
    [key: string]: any
}